### PR TITLE
fix order of operations bug

### PR DESCRIPTION
**Pull request by y2kbugger**
I moved at test code to only run when run as script (as opposed to when imported). Also modified your test case to test what you had in the body. It was correctly evaluating your `if` block to `False`.

Did a hacky way to make make word list text file be visible no matter where you run script from. I was running on phone.

Added .gitignore file cause my editor was sitting in the repo. You can add ignores for vim and pyc files as well so it's easy to commit.

### CODE REVIEW

**Comment by y2kbugger** [comment]
Why didn't you merge?

How can I modify the pull request to meet your expectations?

**Comment by mart00n** [comment]
I didn't understand some of your changes and only took the syntax error fix
to complete the module (i.e. the silly indentation issue).

I meant to work on that this weekend but it was so nice I went all over the
place instead. Kin is taking the same course and its on their new platform
now, and you can get assignments graded free. I need to sign up.

Thanks for helping though, and I understand pull requests and their purpose
a bit better lol.

**Comment by mart00n** [comment]
y2k fix indent bug, add suggessted script code 'guard'

**Comment by y2kbugger** [comment]
Cleaned up the mangling of the working directory and rebased against your latest commit. Should be an easy fast forward merge now.

**Comment by y2kbugger** [comment]
http://stackoverflow.com/questions/419163/what-does-if-name-main-do

**Review by mart00n — APPROVED** [review]
FF merge, thanks y2k

Did not realize your initial instruction was as simple as indenting test statements! XD

**Pull request merged**
